.TH crypto-secretbox-key 1 "October 2010" "nacltools" "NaCl: Networking and Cryptography library"
.SH NAME
.PP
\fBcrypto-secretbox-key\fP \- randomly generate a secret key
.SH SYNOPSIS
.PP
.B crypto-secretbox-key \fIsecretkeyfile\fP 
.SH DESCRIPTION
.PP
Randomly generates a secret key to be used by crypto-secretbox(1) and crypto-secretbox-open(1).  
.PP
The secret key will be written to the file \fIsecretkeyfile\fP
.SH EXIT CODE
.PP
Normally, \fBcrypto-secretbox-key\fP exits with \fB0\fP. 
.PP
If invalid arguments are given, \fBcrypto-secretbox-key\fP exits with \fB100\fP.
.PP
If either \fIsecretkeyfile\fP already exists, or if it refers to an invalid filesystem path, then \fBcrypto-secretbox-key\fP exits with \fB111\fP.
.SH CRYPTOGRAPHY
.PP
This program simply reads random bytes from \fB/dev/urandom\fP to generate a secret key. The number of bytes is equal to the value of \fBcrypto_secretbox_KEYBYTES\fP provided by \fBNaCl\fP, the Networking and Cryptography library by Daniel J. Bernstein and Tanja Lange. See the official website \fIhttp://nacl.cr.yp.to/\fP for details.
.PP
.SH AUTHOR
.PP
Jay Sullivan <jay@petio.org>
.PP
.SH "SEE ALSO"
crypto-secretbox(1) crypto-secretbox-open(1)
