.TH crypto-secretbox 1 "October 2010" "nacltools" "NaCl: Networking and Cryptography library"
.SH NAME
.PP
\fBcrypto-secretbox\fP \- encrypt and authenticate a stream of data using symmetric (secret-key) cryptography
.SH SYNOPSIS
.PP
.B crypto-secretbox \fIsecretkeyfile\fP 
.SH DESCRIPTION
.PP
Reads a stream of data from standard input, and encrypts it using secret-key authenticated cryptography from \fINaCl\fP (the Networking and Cryptography library).  The encrypted data is formatted specifically to be read by crypto-secretbox-open(1).
.PP
The \fIsecretkeyfile\fP argument should point to a file with the secret key.
.SH OUTPUT FORMAT
.PP
Reads input in chunks, and outputs the following for each chunk:
.PP
    \fB1)\fP A nonce for the chunk, encoded as a netstring
.PP
    \fB2)\fP An encrypted chunk, encoded as a netstring
.SH EXIT CODE
.PP
Normally, \fBcrypto-secretbox\fP exits with \fB0\fP. 
.PP
If invalid arguments are given, \fBcrypto-secretbox\fP exits with \fB100\fP.
.PP
If an error occurs, \fBcrypto-secretbox\fP exits with \fB111\fP.
.SH CRYPTOGRAPHY
.PP
This program is a simply a wrapper around the crypto_secretbox function provided by \fBNaCl\fP, the Networking and Cryptography library by Daniel J. Bernstein and Tanja Lange. See the official website \fIhttp://nacl.cr.yp.to/\fP for details.
.SH AUTHOR
Jay Sullivan <jay@petio.org>
.SH "SEE ALSO"
crypto-secretbox-key(1) crypto-secretbox-open(1)
