.TH crypto-secretbox-open 1 "October 2010" "nacltools" "NaCl: Networking and Cryptography library"
.SH NAME
.PP
\fBcrypto-secretbox-open\fP \- verify and decrypt a stream of data using symmetric (secret-key) cryptography
.SH SYNOPSIS
.PP
.B crypto-secretbox-open \fIsecretkeyfile\fP 
.SH DESCRIPTION
.PP
Reads a stream of encrypted data from standard input, and decrypts it using secret-key authenticated cryptography from \fINaCl\fP (the Networking and Cryptography library). Specifically, the encrypted data from standard input is expected to be of the format output by crypto-secretbox(1).
.PP
The \fIsecretkeyfile\fP should point to a file with the secret key.
.SH EXIT CODE
.PP
Normally, \fBcrypto-secretbox-open\fP exits with \fB0\fP. 
.PP
If invalid arguments are given, \fBcrypto-secretbox-open\fP exits with \fB100\fP.
.PP
If an error occurs, \fBcrypto-secretbox-open\fP exits with \fB111\fP.
.SH CRYPTOGRAPHY
.PP
This program is a simply a wrapper around the crypto_secretbox_open function provided by \fBNaCl\fP, the Networking and Cryptography library by Daniel J. Bernstein and Tanja Lange. See the official website \fIhttp://nacl.cr.yp.to/\fP for details.
.SH AUTHOR
Jay Sullivan <jay@petio.org>
.SH "SEE ALSO"
crypto-secretbox-key(1) crypto-secretbox(1)
